### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sjlawton/proj13#1]
It looks like my login information isn't working on Heroku. Did you forget to add the user there?

**Comment by sjlawton** [comment]
This should be resolved now, sorry.

**Comment by chrisvfritz** [comment]
OK, one more thing. It looks like I'm still seeing [an Edit link](https://sheltered-hamlet-5892.herokuapp.com/restaurants/1) on the Show page, which should be hidden when I'm not signed in.

**Comment by sjlawton** [comment]
OK, its fixed now.

**Comment by chrisvfritz** [comment]
:+1: Excellent!
